platform :ios, '9.0'

target 'banner-ads' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for banner-ads
	pod 'Firebase/Core'
	pod 'Firebase/AdMob'
	
end
